---

- name: gnupg package is installed
  apt:
    name: gnupg
    state: present
    install_recommends: no
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"

- name: apt key for NVIDIA is added
  apt_key:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }}/3bf863cc.pub"
    id: 3bf863cc
    state: present

- name: NVIDIA CUDA repository is registered
  apt_repository:
    repo: 'deb http://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_repo_distarch }} /'
    state: present
    filename: cuda
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
  register: nvidia_repo_cuda_apt_repo

- name: NVIDIA Machine Learning repository is registered
  apt_repository:
    repo: 'deb http://developer.download.nvidia.com/compute/machine-learning/repos/{{ nvidia_repo_distarch }} /'
    state: present
    filename: machine-learning
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
